# Generated by Django 3.2.13 on 2022-07-16 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Icon',
        ),
    ]
