# Generated by Django 3.2.13 on 2022-07-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_category_chatroom_likepost_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('idx', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idx')),
                ('schoolName', models.CharField(max_length=50, verbose_name='학교이름')),
                ('addrCode', models.CharField(max_length=256, verbose_name='우편번호')),
                ('addr', models.CharField(max_length=256, verbose_name='집주소')),
                ('detailAddr', models.CharField(max_length=256, verbose_name='상세주소')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updatedDate', models.DateTimeField(blank=True, null=True, verbose_name='수정시간')),
            ],
        ),
        migrations.RemoveField(
            model_name='likepost',
            name='createdDate',
        ),
        migrations.RemoveField(
            model_name='likepost',
            name='updatedDate',
        ),
        migrations.AlterField(
            model_name='post',
            name='count',
            field=models.IntegerField(default=0, verbose_name='방문자 수'),
        ),
    ]
