# Generated by Django 3.2.13 on 2022-07-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20220717_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userRePw',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='사용자재입력pw'),
        ),
    ]
