# Generated by Django 3.2.13 on 2022-07-23 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_user_userrepw'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='schools', verbose_name='이미지경로'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='message',
            field=models.JSONField(blank=True, null=True, verbose_name='메시지내용'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='sellerIdx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='seller_idx', to='post.user', verbose_name='판매자idx'),
        ),
        migrations.AlterField(
            model_name='school',
            name='addr',
            field=models.CharField(max_length=256, verbose_name='학교주소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='addr',
            field=models.CharField(max_length=256, verbose_name='집 주소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='schoolIdx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='post.school', verbose_name='학교idx'),
        ),
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_messages', to='post.user', verbose_name='저자')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('idx', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idx')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_message', to='post.user', verbose_name='저자')),
                ('chatroomIdx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatroom_message', to='post.chatroom', verbose_name='채팅방idx')),
            ],
        ),
    ]
