# Generated by Django 3.2.13 on 2022-07-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20220723_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='schoolIdx',
            field=models.IntegerField(verbose_name='학교idx'),
        ),
    ]
