# Generated by Django 3.2.13 on 2022-07-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='message',
            field=models.JSONField(blank=True, null=True, verbose_name='메시지내용'),
        ),
    ]
