# Generated by Django 3.2.13 on 2022-07-22 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_chatroom_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='tempIdx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='temp_idx', to='post.user', verbose_name='tempIdx'),
        ),
    ]
