# Generated by Django 3.2.13 on 2022-07-23 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_user_schoolidx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bd',
            field=models.DateField(blank=True, null=True, verbose_name='bd'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='생년월일'),
        ),
        migrations.AddField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='전화번호'),
        ),
        migrations.AddField(
            model_name='user',
            name='schoolName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='학교이름'),
        ),
        migrations.CreateModel(
            name='School_User',
            fields=[
                ('idx', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idx')),
                ('userName', models.CharField(blank=True, max_length=10, null=True, verbose_name='사용자이름')),
                ('birthday', models.CharField(blank=True, max_length=15, null=True, verbose_name='생년월일')),
                ('phoneNumber', models.CharField(blank=True, max_length=20, null=True, verbose_name='전화번호')),
                ('schoolIdx', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='post.school', verbose_name='학교idx')),
            ],
        ),
    ]
