# Generated by Django 3.2.13 on 2022-07-22 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_chatroom_tempidx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='tempIdx',
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='sellerIdx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='seller_idx', to='post.user', verbose_name='판매자idx'),
        ),
    ]
