# Generated by Django 3.2.13 on 2022-07-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20220723_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.IntegerField(default=0, verbose_name='좋아요상태'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(default=1, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='user',
            name='addr',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='집 주소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='addrCode',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='우편번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='detailAddr',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='상세주소'),
        ),
    ]
