# Generated by Django 3.2.13 on 2022-07-22 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20220722_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='addr',
            field=models.CharField(max_length=256, verbose_name='학교주소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='addr',
            field=models.CharField(max_length=256, verbose_name='집 주소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='schoolIdx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='post.school', verbose_name='학교idx'),
        ),
    ]
