# Generated by Django 3.2.13 on 2022-07-24 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20220723_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likepost',
            name='status',
        ),
        migrations.AddField(
            model_name='likepost',
            name='like',
            field=models.IntegerField(default=0, verbose_name='상태'),
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('idx', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idx')),
                ('title', models.CharField(max_length=256, verbose_name='제목')),
                ('text', models.TextField(verbose_name='내용')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updatedDate', models.DateTimeField(blank=True, null=True, verbose_name='수정시간')),
                ('userIdx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_idx', to='post.user', verbose_name='저자')),
            ],
        ),
    ]
