# Generated by Django 3.2.13 on 2022-07-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20220723_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likepost',
            name='status',
        ),
        migrations.AddField(
            model_name='likepost',
            name='like',
            field=models.IntegerField(default=0, verbose_name='상태'),
        ),
    ]
