# Generated by Django 3.2.13 on 2022-07-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20220722_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='schools', verbose_name='이미지경로'),
        ),
    ]
