# Generated by Django 3.2.13 on 2022-07-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20220724_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='count',
            field=models.IntegerField(default=0, verbose_name='방문자 수'),
        ),
        migrations.AddField(
            model_name='community',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='communities'),
        ),
    ]
